---
- name: OS upgrade playbook
  hosts: all
  tasks:
#  - name: Copy file hosts with permissions
#    ansible.builtin.copy:
#      src: ./test1
#      dest: /tmp/test1
#      mode: '0644'
#  - name: Add the user 'bob'
#    ansible.builtin.user:
#      name: bob
#    become: yes
#    become_method: sudo
  - name: Prevent kubectl from being upgraded
    become: yes
    dpkg_selections:
      name: kubectl
      selection: hold

  - name: Prevent multiple pkgs from being upgraded
    become: yes
    ansible.builtin.shell: |
        dpkg --set-selections << EOF
        kubelet hold
        kubeadm hold
        EOF

  - name: Upgrade all apt packages
    apt:
      force_apt_get: yes
      upgrade: dist
    become: yes
