---
- name: apt update and install pkg playbook
  hosts: all
  become: true
  tasks:

  - name: update apt cache
    apt:
      update_cache: yes

  - name: install apache2
    apt:
      name: apache2
      state: latest

  - name: remove php for apache
    apt:
      name: libapache2-mod-php
      state: absent

