---
- name: install and rm pkgs playbook
  hosts: all
  become: true
  tasks:

  - name: install pkgs apache2 for Ubuntu
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
        - libapache2-mod-watchcat
      state: latest
      update_cache: yes
        #    when: ansible_distribution == ["Debian", "Ubuntu"]

  - name: remove xsendfile for apache
    package:
      name: 
        - libapache2-mod-xsendfile
      state: absent
        #    when: ansible_distribution == "Ubuntu"

